### ISSUE TITLE
unable to name or rename notes

### ISSUE THREAD

**Issue by travisfw** [CarnetApp/CarnetAndroid#92]
I always get a message "note couldn't be renamed". All my newest notes now do not have names. I have no idea how I might fix this.

**Comment by Irihapeti** [comment]
I'm having the same problem. OS is Resurrection Remix 7.0.2

**Comment by DasIgno** [comment]
Same problem here since a couple of weeks. If it helps, in my case the error first occured, after I began using the Carnet-App in Nextclouds webfrontend in addition to the android app. Before that, Carnet was just installed in my Nextclud instance, but I managed my notes exclusively with the android app. Now I can manage my notes without problems using the web app, while the android app can't re-/name even new notes created within.

**Comment by kariburger** [comment]
I have the same problem.
I can create and rename new notes within the server side carnet app.
But in the Carnet-App in Android I can not rename any (new) note.

Maybe this is relating:
I detect in my access log, that the Carnet-App in Android accesses some wrong paths. It tries to access the files QuickNote/**quickdoc/_quickdoc_**/recentdb/recentnc and
QuickNote/**quickdoc/_quickdoc_**/keywords/keywordsnc .
The server-side Carnet uses the correct paths QuickNote/**quickdoc**/recentdb/recentnc and
QuickNote/**quickdoc**/keywords/keywordsnc .
==> there is a double "/quickdoc" in the path.

I created a symlink at the server, so that the "recentdb" and "keywords" directories are virtually also at the requested place. But this does not solve the problem with the renaming. It just avoids the server response "404" - which caused my fail2ban to trigger bans against myself...

**Comment by PhieF** [comment]
Thx for the report

**Comment by PhieF** [comment]
Should be fixed with c96cfb3060990fd9f6cfa2eb055f4b95ecc712e7

**Comment by kariburger** [comment]
Just to acknowledge the successful fix in the current Version 0.21.0 from F-Droid.
It works now perfect again.

Thanks
