### ISSUE TITLE
[Android App] Add a widget

### ISSUE THREAD

**Issue by sebastienserre** [CarnetApp/CarnetAndroid#98]
Hello,

Should be great to have a widget on the ANdroid App to quickly add a note.

Thx for your great job

**Comment by thardev** [comment]
Hi @PhieF

I'm planning to submit a PR for this issue. I have a working draft right now with the widget displaying a list of the current notes and opening each on the editor if you click on it :)

I used the same design and behaviour as the OmniNotes app is using, I also reused some code from their repo. Since it's GPL licensed I suppose this is acceptable.

Any guidelines in how I should submit my PR? Would be much appreciated :)

Thanks for your work 👍

**Comment by PhieF** [comment]
hi !!

First : thank you very much !

I don't have any guidelines, you can make a PR and I will look at the code and UX, perhaps we will rework it a bit if needed ! 
Thanks again !
